### ISSUE TITLE
EMS v3.75 FW bugged

### ISSUE THREAD

**Issue by davidetome** [robotology/icub-firmware-build#105]
We noticed that the latest `EMS` FW in devel (v3.75)  make the boards stuck in the `eUpdater`.

We need to fix this.

cc @marcoaccame @Nicogene @pattacini @AntonioConsilvio

**Comment by davidetome** [comment]
Just compiled the EMS FW project in the latest devel and it works properly w/o modifying anything. 👍🏻

Probably the binary got corrupted or any mistake in the final manual copy session was made.

**Comment by davidetome** [comment]
Opened a drat PR : 

- https://github.com/robotology/icub-firmware-build/pull/106

cc @marcoaccame @Nicogene

**Comment by marcoaccame** [comment]
> Opened a draft PR :
> 
> * [ems - v.3.75 bug fix (re-generated) #106](https://github.com/robotology/icub-firmware-build/pull/106)
> 
> cc @marcoaccame @Nicogene

merged. thanks @davidetome 


I close the issue but pls anyone feel free to reopen if anything strange happens
