### ISSUE TITLE
Document version of bat corresponding to a given icub-firmware-build release and distro release

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-firmware-build#114]
In https://github.com/robotology/icub-firmware-build#firmware-versioning-table, there is documentation on the mapping between robotology distro release, icub-firmware-build version and board-specific firmware version. This is quite convenient for people operating on the robot to check (manually) if the board are a correct version for the distro used on the robot.

At the moment, it seems that the bat version corresponding to a given distro/icub-firmware release is not documented, it would be great if that could be documented. 

fyi @Nicogene @marcoaccame @davidetome @valegagge @MSECode

**Comment by traversaro** [comment]
For the specific case of icub-firmware-build 1.37.0 / robotology 2023.11.0, I guess the corresponding version of bat is 1.3.2 (based on https://github.com/robotology/icub-firmware-build/commit/2f135d344223e2e08e2e75c9d0d257b4c1c333a3).

**Comment by MSECode** [comment]
> he corresponding version of bat is 1.3.2 (based

Regarding the BAT version that's correct. The latest released BAT version is the 1.3.2.

**Comment by traversaro** [comment]
> > he corresponding version of bat is 1.3.2 (based
> 
> Regarding the BAT version that's correct. The latest released BAT version is the 1.3.2.

Thanks @MSECode, fyi @AntonioConsilvio .

**Comment by traversaro** [comment]
See also the related issue: https://github.com/robotology/icub-firmware-build/issues/115 .
