### ISSUE TITLE
[ergoCubSN002] FirmwareUpdaterCore::getCanBoardsFromEth(): No CAN boards found beneath  "10.0.1.1"  after a successful driver init.

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-firmware-build#178]
After https://github.com/robotology/icub-firmware-build/issues/176, I am trying to manually update the firmware. The update works fine for AMC, MC4PLUS and EMS4, but if I try to flash the CAN boards of a given ETH board, the discover fails with error:

~~~
FirmwareUpdaterCore::getCanBoardsFromEth(): No CAN boards found beneath  "10.0.1.1"  after a successful driver init.
~~~

With @S-Dafarra we assumed this could be a problem related to the fact that the robot was not connected to the battery (and hence to the BMS), but the problem persists after we connected a battery to the robot and rebooted the boards.

**Comment by traversaro** [comment]
It turns out that this is a known problem that already occurred in the past on other ergoCubSN*** robots. As a workaround, we switched the `ergocub002-lap` to have IP `10.0.1.104`, and use switched to use FirmwareUpdater there, and the CAN boards were discovered correctly.

**Comment by S-Dafarra** [comment]
> It turns out that this is a known problem that already occurred in the past on other ergoCubSN*** robots. As a workaround, we switched the `ergocub002-lap` to have IP `10.0.1.104`, and use switched to use FirmwareUpdater there, and the CAN boards were discovered correctly.

Just adding that we also connected via Ethernet to the connector in the leg

**Comment by traversaro** [comment]
> It turns out that this is a known problem that already occurred in the past on other ergoCubSN*** robots. As a workaround, we switched the `ergocub002-lap` to have IP `10.0.1.104`, and use switched to use FirmwareUpdater there, and the CAN boards were discovered correctly.

I think we can track this specific error in https://github.com/robotology/icub-firmware/issues/544 that has a clearer title, as the specific issue described here was solved by a board restart and avoiding a discovery on 10.0.1.1 board, I think we can close the issue.
