### ISSUE TITLE
proposal for commit log of binary files

### ISSUE THREAD

**Issue by marcoaccame** [robotology/icub-firmware-build#3]
The log of the commit should contain some basic information which can help one user to understand the content of the binary file. 

My proposal, open for discussion, is the following.

- first row of the log contains the board name and fw version, so that one can see most important info first.
- in some rows below write info about when the built was done and the SHA of the used repositories. that may be useful to re-create the binary from source code.

- finally add a comment about the differences in functionalities with the previously committed fw version.

An example is in SHA: 4b0356a98d15c6bf66736557bc831b7031c558bf

if we all follow some rule of the sort, the repository will be more clear.

The issue can interest @lornat75 @maggia80 @valegagge @ale-git @randaz81 @davege89

**Comment by traversaro** [comment]
I suggest to also include a blank line between the first row of the commit message and remaining rows, so that some git-related tools can properly work. See http://chris.beams.io/posts/git-commit/#separate .

**Comment by marcoaccame** [comment]
I agree Silvio, it is a good practice.

**Comment by marcoaccame** [comment]
closing it. keep however in mind this mode of commit.
