### ISSUE TITLE
New folder for programming of MC4PLUS

### ISSUE THREAD

**Issue by marcoaccame** [robotology/icub-firmware-build#4]
It is necessary to add a MC4PLUS folder with binaries for the mc4plus board with a structure similar to the EMS folder.

**Comment by marcoaccame** [comment]
added the folder and the environment .hex files with commits up to SHA: aa43935288909ddf164b01d1d2200aede4bc9e82

Please @davege89, can you test programming procedure w/ ULINkpro and add latest mc4plus.hex application?

**Comment by davege89** [comment]
Tested the scripts to erase flash and eeprom, burn the Loader and burn the Updater.
They work properly.
Committed the last fully working version of MC4plus WIP application (mc4plus.hex) inside the proper folder, with SHA: 156403c68e5767ea2f3fef25d29345f8f4d5d355

**Comment by marcoaccame** [comment]
add UL2 support (see issue #2)

**Comment by marcoaccame** [comment]
added w/ SHA: c0b25d207fcaea43d1a44db683375ccb03530499

**Comment by davege89** [comment]
@davidetome and I have tested the new scripts which supports (by default) the UL2 programming device.
They work properly.
I just clarified the compatibility with both programming devices inside the readme.txt (SHA: f4a252a5f98136b5b3420d442d6f2cb84bd961a8).
Closing the issue.
