### ISSUE TITLE
Entry point on documentation for updating EMS firmware

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-firmware-build#7]
I guess the most updated documentation on how to update EMS firmware is the one found in https://github.com/robotology/icub-firmware-build/blob/master/EMS/howto.txt , right? 
If this is the case, I am going to link it from http://wiki.icub.org/wiki/Firmware that is the standard entry point for updating the iCub firmware.

@marcoaccame

**Comment by traversaro** [comment]
@DanielePucci

**Comment by marcoaccame** [comment]
Yes @traversaro,  it is right. Please link it.

**Comment by traversaro** [comment]
:+1:

**Comment by marcoaccame** [comment]
Hi @traversaro, I have just updated the documentation for performing FW update which now is in folder https://github.com/robotology/icub-firmware-build/tree/master/ETH.

I have also updated the page in http://wiki.icub.org/wiki/Firmware to link the new files and announced it in Q/A.

Thus, if it is OK for you I would close the issue.

**Comment by traversaro** [comment]
Yes, great!

**Comment by traversaro** [comment]
Thanks a lot!
